name: Simple CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "this is my command"

      - name: Step_1
        run: echo "this is my step one"

      - name: Step_2
        run: echo "this is my step two"

      - name: Step_3
        run: echo "Pipeline is fixed"

