name: Simple CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "this is my command"

      - name: Step_1
        run: echo "this is my step one"

      - name: Step_2
        run: echo "this is my step two"

      - name: Step_3
        run: echo "Pipeline is fixed"

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/devops-demo:v1 .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.actor }}/devops-demo:v1




    